# Generated by Django 4.2.1 on 2026-05-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Imagen')),
                ('excerpt', models.TextField(verbose_name='Resumen')),
                ('body', models.TextField(blank=True, verbose_name='Contenido')),
                ('published_at', models.DateField(verbose_name='Fecha')),
                ('show_on_home', models.BooleanField(default=True, verbose_name='Mostrar en inicio')),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
                'ordering': ('order', '-published_at', 'id'),
                'abstract': False,
            },
        ),
    ]
